"""One-time v1.3 source derivation; never overwrite user edits on normal builds."""
from pathlib import Path
import re
R=Path(__file__).resolve().parent.parent
A=R/'archive/v1.2-source/three_body_proof'
def change(s,old,new):
    if old not in s: raise ValueError(f'Expected source fragment absent: {old[:70]}')
    return s.replace(old,new)
def write(path,s):
    t=R/path
    if t.exists(): return
    t.parent.mkdir(parents=True,exist_ok=True)
    t.write_text(s,encoding='utf-8')
s=(A/'validated.js').read_text()
s=change(s,'function bounds(X,m)','function bounds(X,m,weighted=true)')
s=change(s,'const L=max(S,8n*sums.map(x=>x[1]).reduce(max));return {L,dmin};','const K=max(S,8n*sums.map(x=>x[1]).reduce(max));const L=weighted?sqrt([K,K])[1]:K;return {L,dmin};')
s=change(s,'order>16','order>28')
s=change(s,'integer 4..16','integer 4..28')
s=change(s,'three-body-interval-certificate-1','three-body-interval-certificate-2')
s=change(s,'1.2.0','1.3.0')
s=change(s,'steps.length>=512','steps.length>=2048')
s=change(s,'512-step','2048-step')
s=change(s,'attemptCount>768','attemptCount>4096')
s=change(s,'768-attempt','4096-attempt')
s=change(s,"cert.schema!=='three-body-interval-certificate-2'","!['three-body-interval-certificate-1','three-body-interval-certificate-2'].includes(cert.schema)")
s=change(s,'const q=validateInput(cert.input);let Y=',"const q=validateInput(cert.input);if(cert.schema==='three-body-interval-certificate-1'&&q.order>16)throw Error('legacy certificate order outside 4..16');let Y=")
s=change(s,'const b=bounds(X,q.m),cq=',"const b=bounds(X,q.m,cert.schema==='three-body-interval-certificate-2'),cq=")
s=change(s,'/* Three Body Lab v1.2:','/* Three Body Lab v1.3:')
s=s.replace('function bounds(X,m,weighted=true)','// Weighted norm max(sqrt(K)*|dr|_inf, |dv|_inf) gives Lipschitz sqrt(K).\nfunction bounds(X,m,weighted=true)')
write('src/validated.js',s)
v=(A/'verify_certificate.py').read_text()
v=change(v,"c.get('schema') != 'three-body-interval-certificate-1'","c.get('schema') not in ('three-body-interval-certificate-1', 'three-body-interval-certificate-2')")
v=change(v,'not 4 <= order <= 16',"not 4 <= order <= (28 if c.get('schema') == 'three-body-interval-certificate-2' else 16)")
v=change(v,'L, distance = lipschitz(X, m)',"L, distance = lipschitz(X, m)\n        if c['schema'] == 'three-body-interval-certificate-2': L = root((L, L))[1]")
write('src/verify_certificate.py',v)
h=(R/'archive/v1.2-source/three_body_lab_v1_2.html').read_text()
h,n=re.subn(r'(<script id="validated-source">).*?(</script>)',lambda m:m[1]+'__VALIDATED_SOURCE__'+m[2],h,flags=re.S)
if n!=1: raise ValueError('Validated source marker missing')
h=h.replace('v1.2','v1.3').replace('value="0.7"','value="1"')
h=change(h,'<option value="14" selected>14</option>','<option value="14">14</option>')
h=change(h,'<option value="16">16</option>','<option value="16">16</option><option value="20" selected>20</option><option value="24">24</option>')
h=change(h,'<option value="8" selected>1 / 256</option>','<option value="8">1 / 256</option>')
h=change(h,'<option value="9">1 / 512</option>','<option value="9" selected>1 / 512</option>')
h=change(h,'512단계 / 768회','2048단계 / 4096회')
h=h.replace('<div class="top-actions">','<div class="top-actions"><a href="research.html" style="color:var(--cyan);padding:8px;text-decoration:none">연구 기록 ↗</a>',1)
h=h.replace('hL &lt; 1','h√K &lt; 1 (가중 노름)')
h=h.replace('위 Picard 포함 조건과 수축 조건을 각 구간에서 검사합니다.','K ≥ max(1, ||Dᵣa||∞), 노름 max(√K||δr||∞, ||δv||∞)에서 위 포함 조건과 수축 조건을 각 구간마다 검사합니다. 이전 형식의 증명서는 기존 비가중 조건으로 재검사합니다.')
write('site/lab-template.html',h)
old=(R/'archive/v1.2-source/three_body_lab_v1_1.html').read_text()
write('archive/v1.2-source/three_body_lab/style.css',re.search(r'<style>(.*?)</style>',old,re.S).group(1))
t=(A/'test_exact.py').read_text()
t=change(t,'from verify_certificate import verify,S',"import sys\nsys.path.insert(0,str(Path(__file__).resolve().parent.parent/'src'))\nfrom verify_certificate import verify,S")
t=t.replace("str(BASE/'validated.js')","str(BASE.parent/'src/validated.js')")
t=t.replace("(BASE/'asymmetric_Tp1.json')","(BASE.parent/'research/results/smoke.json')")
t=t.replace("(BASE/'exact_test_results.json')","(BASE.parent/'research/results/exact_tests.json')")
write('tests/test_exact.py',t)
print('Editable v1.3 files are ready; existing files were not overwritten.')
